### ISSUE TITLE
get_loss

### ISSUE THREAD

**Issue by pzhren** [idejie/OAN#3]
https://github.com/idejie/OAN/blob/b32d122ab09c5eb0dec65780057473842aebce24/utils.py#L107
这个位置是不是不对呢？我觉得应该是for j in range(i+1,v_length):
不然，same_v = same_v.argmin(dim=2)必然是对角线上的和自身的距离最近。期待您的回复

**Comment by idejie** [comment]
很抱歉才回复你，之前我的GitHub账号出现了notification和feed流异常，最近官方才fix了这个bug，以至于才发现你的issue.

我很抱歉的回复你，此repo仅为个人复现，由于和原作者多次沟通代码复现问题无果，加之个人精力有限，故暂停维护此代码。

如果有兴趣，我们可以共同维护。

All Bests. ^_^
